# Generated by Django 5.1.1 on 2024-09-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='logros',
            field=models.TextField(blank=True, null=True),
        ),
    ]
